Tolerate errors for parsing stats as much as possible

diff --git a/parsing-stats/run-all b/parsing-stats/run-all
--- a/parsing-stats/run-all
+++ b/parsing-stats/run-all
@@ -37,20 +37,65 @@ while [[ $# != 0 ]]; do
   shift
 done
 
+pid_map=pids
+rm -f "$pid_map"
+
 # Run the parsing jobs in parallel. Output may be mangled.
 pid_list=''
 for dir in lang/*; do
   lang=$(basename "$dir")
+
   ./run-lang "$lang" $forwarded_option_list &
+
   pid=$!
   pid_list+=" $pid"
+  echo "$pid $lang" >> "$pid_map"
 done
 
+success=true
+exit_statuses=exit-statuses
+rm -f "$exit_statuses"
+
 for pid in $pid_list; do
-  wait "$pid"
+  # Tolerate failures so as to not block the other jobs
+  lang=$(grep "$pid" "$pid_map" | cut -f2)
+  if wait "$pid"; then
+    echo "OK $lang" >> "$exit_statuses"
+  else
+    echo "FAIL $lang" >> "$exit_statuses"
+    success=false
+  fi
 done
+rm -f "$pid_map"
 
 # Show all the results sequentially at the end
 for dir in lang/*; do
-  cat "$dir"/stats.json
+  lang=$(basename "$dir")
+  echo "------ $lang -----"
+  if [[ -e "$dir"/stats.json ]]; then
+    cat "$dir"/stats.json
+  fi
 done
+
+# Same but shorter
+for dir in lang/*; do
+  lang=$(basename "$dir")
+  jsonfile="$dir"/stats.json
+  if [[ -e "$jsonfile" && -n "$(cat "$jsonfile")" ]]; then
+    echo "Language: $lang"
+    echo "Line count: $(jq .global.line_count "$jsonfile")"
+    echo "Parsing rate: $(jq .global.parsing_rate "$jsonfile")"
+  else
+    echo "Language: $lang"
+    echo "no data"
+  fi
+  echo
+done
+
+cat "$exit_statuses"
+rm -f "$exit_statuses"
+
+if [[ "$success" = false ]]; then
+  echo "*** Parsing stats failed for one or more languages." >&2
+  exit 1
+fi
