re-test setup-python

diff --git a/.github/workflows/build-test-osx-m1-cirrus.yaml b/.github/workflows/build-test-osx-m1-cirrus.yaml
--- a/.github/workflows/build-test-osx-m1-cirrus.yaml
+++ b/.github/workflows/build-test-osx-m1-cirrus.yaml
@@ -24,81 +24,81 @@ on:
     - cron: 27 * * * *
 
 jobs:
-  build-core-m1:
-    name: Build the OSX M1 binaries
-    runs-on:
-      [
-        "self-hosted",
-        "macOS",
-        "ARM64",
-        "ghcr.io/cirruslabs/macos-monterey-xcode:latest",
-      ]
-    env:
-      OPAM_SWITCH_NAME: "4.14.0"
-    steps:
-      - name: Setup runner directory
-        run: |
-          sudo mkdir /Users/runner
-          sudo chown admin:staff /Users/runner
-          sudo chmod 750 /Users/runner
-      - name: Cache Brew Cache
-        id: cache-brew
-        uses: actions/cache@v3
-        with:
-          path: |
-            /Users/admin/Library/Caches/Homebrew
-            /opt/homebrew/Cellar/python@3.11
-          key: "${{ runner.os }}-${{ runner.arch }}-brew-cache-E038jVAPUmLOFgsT"
-      - name: Brew Update
-        if: steps.cache-brew.outputs.cache-hit != 'true'
-        run: |
-          brew update
-      - name: Brew Install Python
-        if: steps.cache-brew.outputs.cache-hit != 'true'
-        run: |
-          brew install python@3.11
-      - name: Re-link Python3
-        if: steps.cache-brew.outputs.cache-hit == 'true'
-        run: |
-          brew link python@3.11
-      - name: Debug Info
-        run: |
-          set -x
-          # brew info python3 --json | jq '.[0].name'
-          # brew info python3 --json | jq '.[0].urls.stable.checksum'
-          # brew info python3 --json | jq '.[0].versions.stable'
-          brew --cache
-          brew --prefix
-          which python3
-          ls -al "$(brew --prefix)/bin"
-          python3 --version
-      - uses: actions/checkout@v3
-        with:
-          submodules: true
-      # Note that this action handles both cache read and cache write.
-      # See https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows for more information on GHA caching.
-      - name: Cache Opam
-        id: cache-opam
-        uses: actions/cache@v3
-        if: ${{ inputs.use-cache || github.event_name == 'pull_request' || github.event_name == 'schedule' }}
-        env:
-          SEGMENT_DOWNLOAD_TIMEOUT_MINS: 2
-        with:
-          path: ~/.opam
-          key: "${{ runner.os }}-${{ runner.arch }}-${{ env.OPAM_SWITCH_NAME }}-opam-deps"
-      - name: Install dependencies
-        run: |
-          ./scripts/osx-setup-for-release.sh "${{ env.OPAM_SWITCH_NAME }}"
-      - name: Compile semgrep
-        run: |
-          opam exec -- make core
-          mkdir -p artifacts
-          cp ./bin/semgrep-core artifacts
-          zip -r artifacts.zip artifacts
-      - uses: actions/upload-artifact@v3
-        with:
-          path: artifacts.zip
-          name: semgrep-m1-${{ github.sha }}
+  # build-core-m1:
+  #   name: Build the OSX M1 binaries
+  #   runs-on:
+  #     [
+  #       "self-hosted",
+  #       "macOS",
+  #       "ARM64",
+  #       "ghcr.io/cirruslabs/macos-monterey-xcode:latest",
+  #     ]
+  #   env:
+  #     OPAM_SWITCH_NAME: "4.14.0"
+  #   steps:
+  #     - name: Setup runner directory
+  #       run: |
+  #         sudo mkdir /Users/runner
+  #         sudo chown admin:staff /Users/runner
+  #         sudo chmod 750 /Users/runner
+  #     - name: Cache Brew Cache
+  #       id: cache-brew
+  #       uses: actions/cache@v3
+  #       with:
+  #         path: |
+  #           /Users/admin/Library/Caches/Homebrew
+  #           /opt/homebrew/Cellar/python@3.11
+  #         key: "${{ runner.os }}-${{ runner.arch }}-brew-cache-E038jVAPUmLOFgsT"
+  #     - name: Brew Update
+  #       if: steps.cache-brew.outputs.cache-hit != 'true'
+  #       run: |
+  #         brew update
+  #     - name: Brew Install Python
+  #       if: steps.cache-brew.outputs.cache-hit != 'true'
+  #       run: |
+  #         brew install python@3.11
+  #     - name: Re-link Python3
+  #       if: steps.cache-brew.outputs.cache-hit == 'true'
+  #       run: |
+  #         brew link python@3.11
+  #     - name: Debug Info
+  #       run: |
+  #         set -x
+  #         # brew info python3 --json | jq '.[0].name'
+  #         # brew info python3 --json | jq '.[0].urls.stable.checksum'
+  #         # brew info python3 --json | jq '.[0].versions.stable'
+  #         brew --cache
+  #         brew --prefix
+  #         which python3
+  #         ls -al "$(brew --prefix)/bin"
+  #         python3 --version
+  #     - uses: actions/checkout@v3
+  #       with:
+  #         submodules: true
+  #     # Note that this action handles both cache read and cache write.
+  #     # See https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows for more information on GHA caching.
+  #     - name: Cache Opam
+  #       id: cache-opam
+  #       uses: actions/cache@v3
+  #       if: ${{ inputs.use-cache || github.event_name == 'pull_request' || github.event_name == 'schedule' }}
+  #       env:
+  #         SEGMENT_DOWNLOAD_TIMEOUT_MINS: 2
+  #       with:
+  #         path: ~/.opam
+  #         key: "${{ runner.os }}-${{ runner.arch }}-${{ env.OPAM_SWITCH_NAME }}-opam-deps"
+  #     - name: Install dependencies
+  #       run: |
+  #         ./scripts/osx-setup-for-release.sh "${{ env.OPAM_SWITCH_NAME }}"
+  #     - name: Compile semgrep
+  #       run: |
+  #         opam exec -- make core
+  #         mkdir -p artifacts
+  #         cp ./bin/semgrep-core artifacts
+  #         zip -r artifacts.zip artifacts
+  #     - uses: actions/upload-artifact@v3
+  #       with:
+  #         path: artifacts.zip
+  #         name: semgrep-m1-${{ github.sha }}
 
   build-wheels-m1:
     runs-on:
@@ -108,34 +108,23 @@ jobs:
         "ARM64",
         "ghcr.io/cirruslabs/macos-monterey-base:latest",
       ]
-    needs: [build-core-m1]
     steps:
-      - name: Cache Brew Cache
-        id: cache-brew
-        uses: actions/cache@v3
-        with:
-          path: |
-            /Users/admin/Library/Caches/Homebrew
-            /opt/homebrew/Cellar/python@3.11
-          key: "${{ runner.os }}-${{ runner.arch }}-brew-cache-E038jVAPUmLOFgsT"
-      - name: Brew Update
-        if: steps.cache-brew.outputs.cache-hit != 'true'
+      - name: Setup runner directory
         run: |
-          brew update
-      - name: Brew Install Python
-        if: steps.cache-brew.outputs.cache-hit != 'true'
-        run: |
-          brew install python@3.11
-      - name: Re-link Python3
-        if: steps.cache-brew.outputs.cache-hit == 'true'
-        run: |
-          brew link python@3.11
+          sudo mkdir /Users/runner
+          sudo chown admin:staff /Users/runner
+          sudo chmod 750 /Users/runner
+          sudo mkdir /Users/runner/hostedtoolcache
+          sudo chmod 750 /Users/runner/hostedtoolcache
       - uses: actions/checkout@v3
         with:
           submodules: true
-      - uses: actions/download-artifact@v3
+      - name: Restore Semgrep Core Binary
+        id: cache-semgrep-core
+        uses: actions/cache/restore@v3
         with:
-          name: semgrep-m1-${{ github.sha }}
+          path: artifacts.zip
+          key: osx-m1-semgrep-core-VzlGZQINFX2
       - run: |
           unzip artifacts.zip
           cp artifacts/semgrep-core cli/src/semgrep/bin
@@ -145,57 +134,57 @@ jobs:
           path: cli/dist.zip
           name: m1-wheel
 
-  test-wheels-m1:
-    runs-on:
-      [
-        "self-hosted",
-        "macOS",
-        "ARM64",
-        "ghcr.io/cirruslabs/macos-monterey-base:latest",
-      ]
-    needs: [build-wheels-m1]
-    steps:
-      - uses: actions/download-artifact@v1
-        with:
-          name: m1-wheel
-      - name: Cache Brew Cache
-        id: cache-brew
-        uses: actions/cache@v3
-        with:
-          path: |
-            /Users/admin/Library/Caches/Homebrew
-            /opt/homebrew/Cellar/python@3.11
-          key: "${{ runner.os }}-${{ runner.arch }}-brew-cache-E038jVAPUmLOFgsT"
-      - name: Brew Update
-        if: steps.cache-brew.outputs.cache-hit != 'true'
-        run: |
-          brew update
-      - name: Brew Install Python
-        if: steps.cache-brew.outputs.cache-hit != 'true'
-        run: |
-          brew install python@3.11
-      - name: Re-link Python3
-        if: steps.cache-brew.outputs.cache-hit == 'true'
-        run: |
-          brew link python@3.11
-      - run: unzip ./m1-wheel/dist.zip
-      - name: install package
-        run: pip3 install dist/*.whl
-      - run: semgrep --version
-      - name: e2e semgrep-core test
-        run: echo '1 == 1' | semgrep -l python -e '$X == $X' -
-      - name: test dynamically linked libraries are in /usr/lib/
-        shell: bash {0}
-        run: |
-          otool -L $(semgrep --dump-engine-path) > otool.txt
-          if [ $? -ne 0 ]; then
-            echo "Failed to list dynamically linked libraries.";
-            cat otool.txt;
-            exit 1;
-          fi
-          NON_USR_LIB_DYNAMIC_LIBRARIES=$(cat otool.txt | tail -n +2 | grep -v "^\s*/usr/lib/")
-          if [ $? -eq 0 ]; then
-            echo "Error: semgrep-core has been dynamically linked against libraries outside /usr/lib:"
-            echo $NON_USR_LIB_DYNAMIC_LIBRARIES
-            exit 1;
-          fi;
+  # test-wheels-m1:
+  #   runs-on:
+  #     [
+  #       "self-hosted",
+  #       "macOS",
+  #       "ARM64",
+  #       "ghcr.io/cirruslabs/macos-monterey-base:latest",
+  #     ]
+  #   needs: [build-wheels-m1]
+  #   steps:
+  #     - uses: actions/download-artifact@v1
+  #       with:
+  #         name: m1-wheel
+  #     - name: Cache Brew Cache
+  #       id: cache-brew
+  #       uses: actions/cache@v3
+  #       with:
+  #         path: |
+  #           /Users/admin/Library/Caches/Homebrew
+  #           /opt/homebrew/Cellar/python@3.11
+  #         key: "${{ runner.os }}-${{ runner.arch }}-brew-cache-E038jVAPUmLOFgsT"
+  #     - name: Brew Update
+  #       if: steps.cache-brew.outputs.cache-hit != 'true'
+  #       run: |
+  #         brew update
+  #     - name: Brew Install Python
+  #       if: steps.cache-brew.outputs.cache-hit != 'true'
+  #       run: |
+  #         brew install python@3.11
+  #     - name: Re-link Python3
+  #       if: steps.cache-brew.outputs.cache-hit == 'true'
+  #       run: |
+  #         brew link python@3.11
+  #     - run: unzip ./m1-wheel/dist.zip
+  #     - name: install package
+  #       run: pip3 install dist/*.whl
+  #     - run: semgrep --version
+  #     - name: e2e semgrep-core test
+  #       run: echo '1 == 1' | semgrep -l python -e '$X == $X' -
+  #     - name: test dynamically linked libraries are in /usr/lib/
+  #       shell: bash {0}
+  #       run: |
+  #         otool -L $(semgrep --dump-engine-path) > otool.txt
+  #         if [ $? -ne 0 ]; then
+  #           echo "Failed to list dynamically linked libraries.";
+  #           cat otool.txt;
+  #           exit 1;
+  #         fi
+  #         NON_USR_LIB_DYNAMIC_LIBRARIES=$(cat otool.txt | tail -n +2 | grep -v "^\s*/usr/lib/")
+  #         if [ $? -eq 0 ]; then
+  #           echo "Error: semgrep-core has been dynamically linked against libraries outside /usr/lib:"
+  #           echo $NON_USR_LIB_DYNAMIC_LIBRARIES
+  #           exit 1;
+  #         fi;
