can we use the universal wheel?

diff --git a/.github/workflows/build-test-osx-x86.yaml b/.github/workflows/build-test-osx-x86.yaml
--- a/.github/workflows/build-test-osx-x86.yaml
+++ b/.github/workflows/build-test-osx-x86.yaml
@@ -131,7 +131,7 @@ jobs:
           path: cli/dist.zip
           name: osx-wheel
 
-  test-wheels-osx:
+  test-wheels-osx-x86:
     runs-on: macos-12
     needs: [build-wheels-osx]
     steps:
@@ -144,6 +144,51 @@ jobs:
       - run: semgrep --version
       - name: e2e semgrep-core test
         run: echo '1 == 1' | semgrep --debug -l python -e '$X == $X' -
+      - name: test dynamically linked libraries are in /usr/lib/
+        shell: bash {0}
+        run: |
+          otool -L $(semgrep --dump-engine-path) > otool.txt
+          if [ $? -ne 0 ]; then
+            echo "Failed to list dynamically linked libraries.";
+            cat otool.txt;
+            exit 1;
+          fi
+          NON_USR_LIB_DYNAMIC_LIBRARIES=$(cat otool.txt | tail -n +2 | grep -v "^\s*/usr/lib/")
+          if [ $? -eq 0 ]; then
+            echo "Error: semgrep-core has been dynamically linked against libraries outside /usr/lib:"
+            echo $NON_USR_LIB_DYNAMIC_LIBRARIES
+            exit 1;
+          fi;
+
+  test-wheels-m1:
+    runs-on:
+      [
+        "self-hosted",
+        "macOS",
+        "ARM64",
+        "ghcr.io/cirruslabs/macos-monterey-base:latest",
+      ]
+    needs: [build-wheels-osx]
+    steps:
+      - name: Setup runner directory
+        run: |
+          sudo mkdir /Users/runner
+          sudo chmod 750 /Users/runner
+          sudo mkdir /Users/runner/hostedtoolcache
+          sudo chmod 750 /Users/runner/hostedtoolcache
+          sudo chown -R admin:staff /Users/runner
+      - uses: actions/download-artifact@v1
+        with:
+          name: osx-wheel
+      - uses: actions/setup-python@v4
+        with:
+          python-version: "3.11"
+      - run: unzip ./osx-wheel/dist.zip
+      - name: install package
+        run: pip3 install dist/*.whl
+      - run: semgrep --version
+      - name: e2e semgrep-core test
+        run: echo '1 == 1' | semgrep -l python -e '$X == $X' -
       - name: test dynamically linked libraries are in /usr/lib/
         shell: bash {0}
         run: |
