remove old version of semgrep before running

diff --git a/.github/workflows/homebrew-core-head.yml b/.github/workflows/homebrew-core-head.yml
--- a/.github/workflows/homebrew-core-head.yml
+++ b/.github/workflows/homebrew-core-head.yml
@@ -11,6 +11,10 @@ jobs:
     name: Build Semgrep via Brew from `returntocorp/semgrep:develop`
     runs-on: ["self-hosted", "macOS", "X64"]
     steps:
+      - name: Uninstall semgrep
+        # This is sub-optimal - our workflows shouldn't have to conform to their environment.
+        # However, on the runner side, we can't hook into the workflow run to clean up after.
+        run: brew uninstall semgrep || true
       - name: Brew update
         run: brew update
       - name: Brew Install
