more

diff --git a/.github/workflows/sync-with-PRO.yml b/.github/workflows/sync-with-PRO.yml
--- a/.github/workflows/sync-with-PRO.yml
+++ b/.github/workflows/sync-with-PRO.yml
@@ -39,7 +39,26 @@ jobs:
           BRANCHNAME: sync-with-PRO-${{ github.run_id }}-${{ github.run_attempt }}
           GITHUB_TOKEN: ${{ steps.token.outputs.token }}
         name: Creating the branch and commiting to it
-        run: "if git show --stat develop | grep -q \"synced from Pro\"; then\n   echo \"error: HEAD commit already comes from Pro and cannot be synced\"\n   exit 1\nfi\n# will generate a 0001-xxx patch\ngit format-patch develop^\n\ncd PRO\ngit config --global user.name \"GitHub Actions Bot\"\ngit config --global user.email \"<>\"\ngit checkout -b $BRANCHNAME\n\n# note that this can fail if develop^ is already in Pro\ngit am --directory=OSS ../0001-*\ngit log -1 --pretty=%B >message\necho \"\" >>message \necho \"synced from OSS $(git rev-parse HEAD)\" >>message\ngit commit --amend -F message\ngit push origin $BRANCHNAME\n"
+        run: |
+          if git show --stat develop | grep -q "synced from ProXXX"; then
+             echo "error: HEAD commit already comes from Pro and cannot be synced"
+             exit 1
+          fi
+          # will generate a 0001-xxx patch
+          git format-patch develop^
+
+          cd PRO
+          git config --global user.name "GitHub Actions Bot"
+          git config --global user.email "<>"
+          git checkout -b $BRANCHNAME
+
+          # note that this can fail if develop^ is already in Pro
+          git am --directory=OSS ../0001-*
+          git log -1 --pretty=%B >message
+          echo "" >>message
+          echo "synced from OSS $(git rev-parse HEAD)" >>message
+          git commit --amend -F message
+          git push origin $BRANCHNAME
       - env:
           GITHUB_TOKEN: ${{ steps.token.outputs.token }}
         name: Create the Pull request with gh
